//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarApp.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string NumeroSesion { get; set; }
        public int IdPaciente { get; set; }
        public int IdPrestador { get; set; }
        public float Monto { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Prestador Prestador { get; set; }
    }
}
